name = 'cf-workers-sub'
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "f6292e118bbc49128afcbab4b16d37fd"					#KV据库id
